---
- name: Installing Zsh and git
  become: yes
  apt: name=zsh,git state=latest
  register: installation

- name: Backing up existing ~/.zshrc
  shell: if [ -f ~/.zshrc ]; then mv ~/.zshrc{,.orig}; fi
  when: installation|changed

- name: Installing oh-my-zsh
  shell: "wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -"
  when: installation|changed

- name: Making zsh default shell
  become: yes
  shell: chsh -s /usr/bin/zsh
  when: installation|changed
